export const GET_CONTACTs_SUCCESS = "GET_CONTACTs_SUCCESS";
export const GET_CONTACTs_LOAD = "GET_CONTACTs_LOAD";
export const GET_CONTACTs_FAIL = "GET_CONTACTs_FAIL";
export const GET_ONE_CONTACT ="GET_ONE_CONTACT";